version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAJMSANDGITTestProject
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: SSL_JDBC_Test
  gitServerName: kusiAWSStage1
  gitUrl: https://github.com/prabhakarsag
  gitUsername: Rajni25Aug
  gitBranch: main
